### ISSUE TITLE
[Core]: Nimbus crashes on updating CEL for the resource which is not present

### ISSUE THREAD

**Issue by anurag-rajawat** [5GSEC/nimbus#59]
## Description
If we specify the CEL expression to select resources in the SecurityIntentBinding (SIB) selector and if there is a typo or the resource itself doesn't exist in the cluster then nimbus crashes.

## Steps to reproduce
1. Run nimbus
```shell
make run
```
3. Apply cel-based SI + SIB
```shell
kubectl apply -f  examples/namespaced/cel-multi-si-sib-namespaced.yaml
```
4. Edit SIB selector's CEL for a resource that doesn't exist or try a typo.
E.g., `labels["app"] == "nginx"` to ` labels["app"] == "ngin"`
```shell
kubectl edit sib multiple-sis-nsscoped-binding
```
and then nimbus crashes with following logs:
```shell
...
2024-02-14T15:09:29+05:30       ERROR   No labels matched the CEL expressions, aborting NimbusPolicy creation due to missing keys in labels     {"controller": "securityintentbinding", "controllerGroup": "intent.security.nimbus.com", "controllerKind": "SecurityIntentBinding", "SecurityIntentBinding": {"name":"multiple-sis-nsscoped-binding","namespace":"default"}, "namespace": "default", "name": "multiple-sis-nsscoped-binding", "reconcileID": "01a3e488-1554-485a-ac60-23ce451636e6"}
github.com/5GSEC/nimbus/pkg/processor/policybuilder.BuildNimbusPolicy
        /Users/anurag/workspace/nimbus/pkg/processor/policybuilder/nimbuspolicy_builder.go:76
github.com/5GSEC/nimbus/internal/controller.(*SecurityIntentBindingReconciler).Reconcile
        /Users/anurag/workspace/nimbus/internal/controller/securityintentbinding_controller.go:66
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227
2024-02-14T15:09:29+05:30       INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "securityintentbinding", "controllerGroup": "intent.security.nimbus.com", "controllerKind": "SecurityIntentBinding", "SecurityIntentBinding": {"name":"multiple-sis-nsscoped-binding","namespace":"default"}, "namespace": "default", "name": "multiple-sis-nsscoped-binding", "reconcileID": "01a3e488-1554-485a-ac60-23ce451636e6"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x78 pc=0x101b66904]

goroutine 125 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:116 +0x1a4
panic({0x101f9dc40?, 0x102ef3460?})
        /opt/homebrew/opt/go/libexec/src/runtime/panic.go:914 +0x218
github.com/5GSEC/nimbus/internal/controller.(*SecurityIntentBindingReconciler).Reconcile(0x1400000fd28, {0x1021f81b0, 0x1400020ac60}, {{{0x140003283e0?, 0x5?}, {0x140006e6380?, 0x14000741cf8?}}})
        /Users/anurag/workspace/nimbus/internal/controller/securityintentbinding_controller.go:81 +0x604
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1021fbe40?, {0x1021f81b0?, 0x1400020ac60?}, {{{0x140003283e0?, 0xb?}, {0x140006e6380?, 0x0?}}})
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x140006a0500, {0x1021f81e8, 0x140004dbae0}, {0x102024000?, 0x140000ce6c0?})
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316 +0x2e8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x140006a0500, {0x1021f81e8, 0x140004dbae0})
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266 +0x16c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 77
        /Users/anurag/.local/share/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:223 +0x43c
exit status 2
make: *** [run] Error 1
```

## Expected behaviour
Nimbus should handle gracefully scenarios where resources referenced in CEL expressions are either missing or contain typos.

**Comment by anurag-rajawat** [comment]
We can use [utilruntime.HandleCrash()](https://github.com/kubernetes/apimachinery/blob/665c1a23c2ec37c128eef6e2a247c0afae253399/pkg/util/runtime/runtime.go#L46) function to prevent nimbus from crashing like:
```go
func (r *SecurityIntentBindingReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
       // don't let panics crash the process
      defer utilruntime.HandleCrash()
      logger := log.FromContext(ctx)
      
     // business logic
}
```
